info:
  contact: {}
paths:
  /api/v1/position/course:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Присвоение создано
          schema:
            type: string
        "400":
          description: Неверный формат запроса
          schema: {}
        "401":
          description: Пользователь не является сотрудником компании
          schema: {}
        "500":
          description: Внутренняя ошибка сервера
          schema: {}
      summary: Присвоение курса к должности
swagger: "2.0"
