// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/impl/user_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/impl/user_service.go -destination=mocks//service/impl/user_service.go
//
// Package mock_impl is a generated GoMock package.
package mock_impl
