// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/pg/position_storage.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/pg/position_storage.go -destination=mocks/store/pg/position_storage.go
//
// Package mock_pg is a generated GoMock package.
package mock_pg
