// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/config.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/config.go -destination=mocks//config/config.go
//
// Package mock_config is a generated GoMock package.
package mock_config
