// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/code.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/code.go -destination=mocks//model/code.go
//
// Package mock_model is a generated GoMock package.
package mock_model
