// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/company.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/company.go -destination=mocks/model/company.go
//
// Package mock_model is a generated GoMock package.
package mock_model
