// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/course.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/course.go -destination=mocks/model/course.go
//
// Package mock_model is a generated GoMock package.
package mock_model
