// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/error.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/error.go -destination=mocks//model/error.go
//
// Package mock_model is a generated GoMock package.
package mock_model
