// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/token.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/token.go -destination=mocks//model/token.go
//
// Package mock_model is a generated GoMock package.
package mock_model
