// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/doar/smtp-sender/smtp.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/doar/smtp-sender/smtp.go -destination=mocks//pkg/doar/smtp-sender/smtp.go
//
// Package mock_smtpsender is a generated GoMock package.
package mock_smtpsender
