// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/randomseq/randomseq.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/randomseq/randomseq.go -destination=mocks/pkg/randomseq/randomseq.go
//
// Package mock_randomseq is a generated GoMock package.
package mock_randomseq
