// Code generated by MockGen. DO NOT EDIT.
// Source: internal/errs/errs.go
//
// Generated by this command:
//
//	mockgen -source=internal/errs/errs.go -destination=mocks//errs/errs.go
//
// Package mock_errs is a generated GoMock package.
package mock_errs
