// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/access/access.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/access/access.go -destination=mocks//pkg/access/access.go
//
// Package mock_access is a generated GoMock package.
package mock_access
