// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/course_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/course_repo.go -destination=mocks/store/course_repo.go
//
// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	model "github.com/training-of-new-employees/qon/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryCourse is a mock of RepositoryCourse interface.
type MockRepositoryCourse struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryCourseMockRecorder
}

// MockRepositoryCourseMockRecorder is the mock recorder for MockRepositoryCourse.
type MockRepositoryCourseMockRecorder struct {
	mock *MockRepositoryCourse
}

// NewMockRepositoryCourse creates a new mock instance.
func NewMockRepositoryCourse(ctrl *gomock.Controller) *MockRepositoryCourse {
	mock := &MockRepositoryCourse{ctrl: ctrl}
	mock.recorder = &MockRepositoryCourseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryCourse) EXPECT() *MockRepositoryCourseMockRecorder {
	return m.recorder
}

// CompanyCourses mocks base method.
func (m *MockRepositoryCourse) CompanyCourses(ctx context.Context, companyID int) ([]model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompanyCourses", ctx, companyID)
	ret0, _ := ret[0].([]model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompanyCourses indicates an expected call of CompanyCourses.
func (mr *MockRepositoryCourseMockRecorder) CompanyCourses(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyCourses", reflect.TypeOf((*MockRepositoryCourse)(nil).CompanyCourses), ctx, companyID)
}

// CreateCourse mocks base method.
func (m *MockRepositoryCourse) CreateCourse(ctx context.Context, course model.CourseSet) (*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCourse", ctx, course)
	ret0, _ := ret[0].(*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCourse indicates an expected call of CreateCourse.
func (mr *MockRepositoryCourseMockRecorder) CreateCourse(ctx, course any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCourse", reflect.TypeOf((*MockRepositoryCourse)(nil).CreateCourse), ctx, course)
}

// EditCourse mocks base method.
func (m *MockRepositoryCourse) EditCourse(ctx context.Context, course model.CourseSet, companyID int) (*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditCourse", ctx, course, companyID)
	ret0, _ := ret[0].(*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditCourse indicates an expected call of EditCourse.
func (mr *MockRepositoryCourseMockRecorder) EditCourse(ctx, course, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCourse", reflect.TypeOf((*MockRepositoryCourse)(nil).EditCourse), ctx, course, companyID)
}

// UserCourses mocks base method.
func (m *MockRepositoryCourse) UserCourses(ctx context.Context, userID int) ([]model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCourses", ctx, userID)
	ret0, _ := ret[0].([]model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserCourses indicates an expected call of UserCourses.
func (mr *MockRepositoryCourseMockRecorder) UserCourses(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCourses", reflect.TypeOf((*MockRepositoryCourse)(nil).UserCourses), ctx, userID)
}
