// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/lesson_repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/lesson_repo.go -destination=mocks/store/lesson_repo.go
//

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	model "github.com/training-of-new-employees/qon/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryLesson is a mock of RepositoryLesson interface.
type MockRepositoryLesson struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryLessonMockRecorder
}

// MockRepositoryLessonMockRecorder is the mock recorder for MockRepositoryLesson.
type MockRepositoryLessonMockRecorder struct {
	mock *MockRepositoryLesson
}

// NewMockRepositoryLesson creates a new mock instance.
func NewMockRepositoryLesson(ctrl *gomock.Controller) *MockRepositoryLesson {
	mock := &MockRepositoryLesson{ctrl: ctrl}
	mock.recorder = &MockRepositoryLessonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryLesson) EXPECT() *MockRepositoryLessonMockRecorder {
	return m.recorder
}

// CreateLesson mocks base method.
func (m *MockRepositoryLesson) CreateLesson(ctx context.Context, lesson model.Lesson, userID int) (*model.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLesson", ctx, lesson, userID)
	ret0, _ := ret[0].(*model.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLesson indicates an expected call of CreateLesson.
func (mr *MockRepositoryLessonMockRecorder) CreateLesson(ctx, lesson, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLesson", reflect.TypeOf((*MockRepositoryLesson)(nil).CreateLesson), ctx, lesson, userID)
}

// GetLesson mocks base method.
func (m *MockRepositoryLesson) GetLesson(ctx context.Context, lessonID int) (*model.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLesson", ctx, lessonID)
	ret0, _ := ret[0].(*model.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLesson indicates an expected call of GetLesson.
func (mr *MockRepositoryLessonMockRecorder) GetLesson(ctx, lessonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLesson", reflect.TypeOf((*MockRepositoryLesson)(nil).GetLesson), ctx, lessonID)
}

// GetLessonsList mocks base method.
func (m *MockRepositoryLesson) GetLessonsList(ctx context.Context, courseID int) ([]model.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLessonsList", ctx, courseID)
	ret0, _ := ret[0].([]model.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLessonsList indicates an expected call of GetLessonsList.
func (mr *MockRepositoryLessonMockRecorder) GetLessonsList(ctx, courseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLessonsList", reflect.TypeOf((*MockRepositoryLesson)(nil).GetLessonsList), ctx, courseID)
}

// GetUserLessonsStatus mocks base method.
func (m *MockRepositoryLesson) GetUserLessonsStatus(ctx context.Context, userID, courseID int, lessonsIds []int) (map[int]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLessonsStatus", ctx, userID, courseID, lessonsIds)
	ret0, _ := ret[0].(map[int]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLessonsStatus indicates an expected call of GetUserLessonsStatus.
func (mr *MockRepositoryLessonMockRecorder) GetUserLessonsStatus(ctx, userID, courseID, lessonsIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLessonsStatus", reflect.TypeOf((*MockRepositoryLesson)(nil).GetUserLessonsStatus), ctx, userID, courseID, lessonsIds)
}

// UpdateLesson mocks base method.
func (m *MockRepositoryLesson) UpdateLesson(ctx context.Context, lesson model.LessonUpdate) (*model.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLesson", ctx, lesson)
	ret0, _ := ret[0].(*model.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLesson indicates an expected call of UpdateLesson.
func (mr *MockRepositoryLessonMockRecorder) UpdateLesson(ctx, lesson any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLesson", reflect.TypeOf((*MockRepositoryLesson)(nil).UpdateLesson), ctx, lesson)
}

// UpdateUserLessonStatus mocks base method.
func (m *MockRepositoryLesson) UpdateUserLessonStatus(ctx context.Context, userID, courseID, lessonID int, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLessonStatus", ctx, userID, courseID, lessonID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLessonStatus indicates an expected call of UpdateUserLessonStatus.
func (mr *MockRepositoryLessonMockRecorder) UpdateUserLessonStatus(ctx, userID, courseID, lessonID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLessonStatus", reflect.TypeOf((*MockRepositoryLesson)(nil).UpdateUserLessonStatus), ctx, userID, courseID, lessonID, status)
}
