// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/lesson_repo.go

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/training-of-new-employees/qon/internal/model"
)

// MockRepositoryLesson is a mock of RepositoryLesson interface.
type MockRepositoryLesson struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryLessonMockRecorder
}

// MockRepositoryLessonMockRecorder is the mock recorder for MockRepositoryLesson.
type MockRepositoryLessonMockRecorder struct {
	mock *MockRepositoryLesson
}

// NewMockRepositoryLesson creates a new mock instance.
func NewMockRepositoryLesson(ctrl *gomock.Controller) *MockRepositoryLesson {
	mock := &MockRepositoryLesson{ctrl: ctrl}
	mock.recorder = &MockRepositoryLessonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryLesson) EXPECT() *MockRepositoryLessonMockRecorder {
	return m.recorder
}

// CreateLesson mocks base method.
func (m *MockRepositoryLesson) CreateLesson(ctx context.Context, lesson model.Lesson, user_id int) (*model.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLesson", ctx, lesson, user_id)
	ret0, _ := ret[0].(*model.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLesson indicates an expected call of CreateLesson.
func (mr *MockRepositoryLessonMockRecorder) CreateLesson(ctx, lesson, user_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLesson", reflect.TypeOf((*MockRepositoryLesson)(nil).CreateLesson), ctx, lesson, user_id)
}

// GetLesson mocks base method.
func (m *MockRepositoryLesson) GetLesson(ctx context.Context, lessonID int) (*model.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLesson", ctx, lessonID)
	ret0, _ := ret[0].(*model.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLesson indicates an expected call of GetLesson.
func (mr *MockRepositoryLessonMockRecorder) GetLesson(ctx, lessonID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLesson", reflect.TypeOf((*MockRepositoryLesson)(nil).GetLesson), ctx, lessonID)
}

// GetLessonsList mocks base method.
func (m *MockRepositoryLesson) GetLessonsList(ctx context.Context, courseID int) ([]*model.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLessonsList", ctx, courseID)
	ret0, _ := ret[0].([]*model.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLessonsList indicates an expected call of GetLessonsList.
func (mr *MockRepositoryLessonMockRecorder) GetLessonsList(ctx, courseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLessonsList", reflect.TypeOf((*MockRepositoryLesson)(nil).GetLessonsList), ctx, courseID)
}

// UpdateLesson mocks base method.
func (m *MockRepositoryLesson) UpdateLesson(ctx context.Context, lesson model.LessonUpdate) (*model.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLesson", ctx, lesson)
	ret0, _ := ret[0].(*model.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLesson indicates an expected call of UpdateLesson.
func (mr *MockRepositoryLessonMockRecorder) UpdateLesson(ctx, lesson interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLesson", reflect.TypeOf((*MockRepositoryLesson)(nil).UpdateLesson), ctx, lesson)
}
