services:
  postgres:
    container_name: dev_db_qon
    image: postgres:14.3-alpine
    ports:
      - "15438:5432"
    environment:
      POSTGRES_DB: qon_dev
      PGDATABASE: qon_dev
      POSTGRES_USER: qon_dev
      PGUSER: qon
      POSTGRES_PASSWORD: qon
    volumes:
      - dev-db-qon:/var/lib/postgresql/data

volumes:
  dev-db-qon:
