// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/app.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/app.go -destination=mocks/app/app.go
//
// Package mock_app is a generated GoMock package.
package mock_app
