// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/random-digit/random-digit.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/random-digit/random-digit.go -destination=mocks//pkg/random-digit/random-digit.go
//
// Package mock_randomdigit is a generated GoMock package.
package mock_randomdigit
