// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/doar/api-sender/api-sender.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/doar/api-sender/api-sender.go -destination=mocks/pkg/doar/api-sender/api-sender.go
//
// Package mock_apisender is a generated GoMock package.
package mock_apisender
