// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/rest/dummy.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/rest/dummy.go -destination=mocks/app/rest/dummy.go
//
// Package mock_rest is a generated GoMock package.
package mock_rest
