// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/rest/user_handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/rest/user_handler.go -destination=mocks//app/rest/user_handler.go
//
// Package mock_rest is a generated GoMock package.
package mock_rest
