// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/jwttoken/bearer.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/jwttoken/bearer.go -destination=mocks//pkg/jwttoken/bearer.go
//
// Package mock_jwttoken is a generated GoMock package.
package mock_jwttoken
