// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pkg/jwttoken/token_validator.go
//
// Generated by this command:
//
//	mockgen -source=internal/pkg/jwttoken/token_validator.go -destination=mocks/pkg/jwttoken/token_validator.go
//
// Package mock_jwttoken is a generated GoMock package.
package mock_jwttoken
