// Code generated by MockGen. DO NOT EDIT.
// Source: internal/utils/utils.go
//
// Generated by this command:
//
//	mockgen -source=internal/utils/utils.go -destination=mocks//utils/utils.go
//
// Package mock_utils is a generated GoMock package.
package mock_utils
