// Code generated by MockGen. DO NOT EDIT.
// Source: internal/logger/logger.go
//
// Generated by this command:
//
//	mockgen -source=internal/logger/logger.go -destination=mocks//logger/logger.go
//
// Package mock_logger is a generated GoMock package.
package mock_logger
