name: CD

on:
  push:
    branches: [ "deploy", "develop", "main" ]
  workflow_run:
    workflows: ["Create and publish a Docker image"]
    branches: [ "deploy", "develop", "main" ]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Upload repo
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "~"
    - name: (Re)Generate certificates
      uses: appleboy/ssh-action@v1.0.0
      env:
        DOMAIN: ${{ secrets.HOST }}
        MAIL: ${{ secrets.MAIL }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: DOMAIN,MAIL
        script: |
          docker compose --file docker-compose/deploy/gen-certs.yml up --abort-on-container-exit
          
    - name: Rerun server
      uses: appleboy/ssh-action@v1.0.0
      env:
        DOMAIN: ${{ secrets.HOST }}
        SENDER_API_KEY: ${{ secrets.SENDER_API_KEY }}
        FRONT_TAG: ${{ vars.FRONT_TAG }}
        BACK_TAG: ${{ github.ref_name }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: DOMAIN,SENDER_API_KEY,FRONT_TAG,BACK_TAG
        script: |
          echo "FRONT:${FRONT_TAG} BACK:${BACK_TAG}"
          docker compose --file docker-compose/deploy/docker-compose.yml up --pull always -d --remove-orphans
