name: go-checks
on:
  push:
    branches:
      [ "main", "develop" ]
  pull_request:
      branches:
        [ "main", "develop" ]

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.54
  go-fmt:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Install dependency
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/swaggo/swag/cmd/swag@latest 
      - name: Go Vet
        run: go vet ./...
      - name: Go Format
        run: |
          gofmt -s -w . && git diff --exit-code
          goimports -w . && git diff --exit-code
      - name: Check swagger comments
        run: |
          swag fmt && git diff --exit-code
          swag init -g ./internal/app/rest/handlers.go && git diff --exit-code
  go-mod-check:
    name: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify # Prevent supply chain attacks
        run: go mod verify
  go-tests:
    name: tests
    
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: qon_test
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
            - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: Run tests
        env:
          TEST_DB_DSN: postgres://postgres:postgres@localhost:5432/qon_test?sslmode=disable
        run: |
          go test -count 1 -cover -race ./...
